import React, { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import HomeView from "../components/HomeView";
import Phase1View from "../components/Phase1View";
import Phase2View from "../components/Phase2View";
import Phase3View from "../components/Phase3View";
import Phase4View from "../components/Phase4View";
import Phase5View from "../components/Phase5View";
import CompletionView from "../components/CompletionView";
import AutoWriteView from "../components/AutoWriteView";
import * as pipelineService from "../services/pipelineService";

// LocalStorage key for saved articles
const STORAGE_KEY = "nova_saved_articles";

const PipelineContainer = ({ onLogout, onComplete }) => {
  // Pipeline state
  // -1 = AutoWrite, 0 = Home, 1-5 = Phases, 6 = Completion
  const [currentPhase, setCurrentPhase] = useState(0);
  const [pipelineData, setPipelineData] = useState({
    source: null,
    angle: null,
    draft: null,
    proofread: null,
    revised: null,
    title: null,
  });

  // Saved articles state
  const [savedArticles, setSavedArticles] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  // Loading states for API calls
  const [isLoading, setIsLoading] = useState({
    analysis: false,
    draft: false,
    proofread: false,
    revise: false,
    titles: false,
  });

  // Mock AI response data (in production, these come from API)
  const [analysisResult, setAnalysisResult] = useState(null);
  const [generatedDraft, setGeneratedDraft] = useState(null);
  const [proofreadResult, setProofreadResult] = useState(null);
  const [revisedResult, setRevisedResult] = useState(null);
  const [titleSuggestions, setTitleSuggestions] = useState(null);

  // Start pipeline from home
  const handleStartPipeline = useCallback(() => {
    setCurrentPhase(1);
  }, []);

  // Start auto write mode
  const handleAutoWrite = useCallback(() => {
    setCurrentPhase(-1);
  }, []);

  // Auto write complete - go to completion view
  const handleAutoWriteComplete = useCallback((data) => {
    const finalData = {
      source: null,
      angle: null,
      draft: data.article,
      proofread: null,
      revised: null,
      title: data.title,
      finalArticle: data.article,
      isAutoGenerated: true,
    };

    setPipelineData(finalData);
    setCurrentPhase(6);

    if (onComplete) {
      onComplete(finalData);
    }
  }, [onComplete]);

  // Quick action handlers
  const handleQuickAction = useCallback((actionId) => {
    switch (actionId) {
      case "title":
        // Jump directly to title generation
        setCurrentPhase(5);
        break;
      case "proofread":
        // Jump to Phase 4 for proofreading
        setCurrentPhase(4);
        break;
      case "revise":
        // Jump to Phase 4 for revision
        setCurrentPhase(4);
        break;
      default:
        break;
    }
  }, []);

  // Phase navigation
  const handlePhaseClick = useCallback((phase) => {
    if (phase <= currentPhase) {
      setCurrentPhase(phase);
    }
  }, [currentPhase]);

  // Phase 1: Source input complete
  const handlePhase1Complete = useCallback(async (data) => {
    setPipelineData((prev) => ({ ...prev, source: data }));
    setIsLoading((prev) => ({ ...prev, analysis: true }));

    try {
      // Call real API for analysis
      const result = await pipelineService.analyzeSource(
        data.sourceText,
        data.sourceType || 'press_release'
      );
      setAnalysisResult(result);
      setIsLoading((prev) => ({ ...prev, analysis: false }));
      setCurrentPhase(2);
    } catch (error) {
      console.error('Analysis failed:', error);
      setIsLoading((prev) => ({ ...prev, analysis: false }));
      // Show error to user (could add error state)
      alert('소재 분석에 실패했습니다. 다시 시도해주세요.');
    }
  }, []);

  // Phase 2: Framework selection complete
  const handlePhase2Complete = useCallback(async (data) => {
    setPipelineData((prev) => ({ ...prev, angle: data }));
    setIsLoading((prev) => ({ ...prev, draft: true }));
    setCurrentPhase(3);

    try {
      // Call real API for draft generation
      const result = await pipelineService.generateDraft(
        pipelineData.source?.sourceText || '',
        data.selectedAngle,
        'corporate'
      );
      setGeneratedDraft(result.draft);
      setPipelineData((prev) => ({ ...prev, draft: result.draft }));
      setIsLoading((prev) => ({ ...prev, draft: false }));
    } catch (error) {
      console.error('Draft generation failed:', error);
      setIsLoading((prev) => ({ ...prev, draft: false }));
      alert('초안 생성에 실패했습니다. 다시 시도해주세요.');
    }
  }, [pipelineData.source]);

  // Phase 3: Draft complete
  const handlePhase3Complete = useCallback(async (data) => {
    setPipelineData((prev) => ({ ...prev, draft: data.draft }));
    setIsLoading((prev) => ({ ...prev, proofread: true }));
    setCurrentPhase(4);

    try {
      // Call real API for proofreading and revision in parallel
      const [proofResult, reviseResult] = await Promise.all([
        pipelineService.proofreadArticle(data.draft, 'economy'),
        pipelineService.reviseArticle(data.draft, 'medium'),
      ]);

      setProofreadResult(proofResult);
      setRevisedResult(reviseResult);
      setIsLoading((prev) => ({ ...prev, proofread: false }));
    } catch (error) {
      console.error('Proofread/Revise failed:', error);
      setIsLoading((prev) => ({ ...prev, proofread: false }));
      alert('교열/퇴고 처리에 실패했습니다. 다시 시도해주세요.');
    }
  }, []);

  // Phase 4: Proofread/Revise complete
  const handlePhase4Complete = useCallback(async (data) => {
    setPipelineData((prev) => ({ ...prev, proofread: data }));
    setIsLoading((prev) => ({ ...prev, titles: true }));
    setCurrentPhase(5);

    try {
      // Use revised or corrected text for title generation
      const articleText = revisedResult?.revised || proofreadResult?.corrected || pipelineData.draft;
      const result = await pipelineService.generateTitles(articleText, 3);
      setTitleSuggestions(result.titles);
      setIsLoading((prev) => ({ ...prev, titles: false }));
    } catch (error) {
      console.error('Title generation failed:', error);
      setIsLoading((prev) => ({ ...prev, titles: false }));
      alert('제목 생성에 실패했습니다. 다시 시도해주세요.');
    }
  }, [revisedResult, proofreadResult, pipelineData.draft]);

  // Phase 5: Complete - Move to completion view
  const handlePipelineComplete = useCallback((data) => {
    const finalData = {
      ...pipelineData,
      title: data.title,
      finalArticle: data.article,
    };

    setPipelineData(finalData);
    setCurrentPhase(6); // Move to completion view

    // Also call external onComplete if provided
    if (onComplete) {
      onComplete(finalData);
    }
  }, [pipelineData, onComplete]);

  // Start new article from completion view
  const handleNewArticle = useCallback(() => {
    setCurrentPhase(0);
    setPipelineData({
      source: null,
      angle: null,
      draft: null,
      proofread: null,
      revised: null,
      title: null,
    });
    setAnalysisResult(null);
    setGeneratedDraft(null);
    setProofreadResult(null);
    setRevisedResult(null);
    setTitleSuggestions(null);
  }, []);

  // Save article to localStorage
  const handleSaveArticle = useCallback((article) => {
    setSavedArticles((prev) => {
      const updated = [article, ...prev.filter((a) => a.id !== article.id)];
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      return updated;
    });
  }, []);

  // Load saved article
  const handleLoadArticle = useCallback((article) => {
    // For now, just show the article in completion view
    setPipelineData({
      source: null,
      angle: null,
      draft: article.body,
      proofread: null,
      revised: null,
      title: article.title,
      finalArticle: article.body,
    });
    setCurrentPhase(6);
  }, []);

  // Delete saved article
  const handleDeleteArticle = useCallback((articleId) => {
    setSavedArticles((prev) => {
      const updated = prev.filter((a) => a.id !== articleId);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      return updated;
    });
  }, []);

  // Go to home from any phase
  const handleGoHome = useCallback(() => {
    setCurrentPhase(0);
  }, []);

  // Regenerate handlers
  const handleRegenerateDraft = useCallback(async () => {
    if (!pipelineData.source?.sourceText || !pipelineData.angle?.selectedAngle) return;

    setIsLoading((prev) => ({ ...prev, draft: true }));
    try {
      const result = await pipelineService.generateDraft(
        pipelineData.source.sourceText,
        pipelineData.angle.selectedAngle,
        'corporate'
      );
      setGeneratedDraft(result.draft);
      setPipelineData((prev) => ({ ...prev, draft: result.draft }));
    } catch (error) {
      console.error('Regenerate draft failed:', error);
      alert('초안 재생성에 실패했습니다.');
    }
    setIsLoading((prev) => ({ ...prev, draft: false }));
  }, [pipelineData.source, pipelineData.angle]);

  const handleReprocess = useCallback(async () => {
    if (!pipelineData.draft) return;

    setIsLoading((prev) => ({ ...prev, proofread: true }));
    try {
      const [proofResult, reviseResult] = await Promise.all([
        pipelineService.proofreadArticle(pipelineData.draft, 'economy'),
        pipelineService.reviseArticle(pipelineData.draft, 'medium'),
      ]);
      setProofreadResult(proofResult);
      setRevisedResult(reviseResult);
    } catch (error) {
      console.error('Reprocess failed:', error);
      alert('재처리에 실패했습니다.');
    }
    setIsLoading((prev) => ({ ...prev, proofread: false }));
  }, [pipelineData.draft]);

  const handleRegenerateTitles = useCallback(async () => {
    const articleText = revisedResult?.revised || proofreadResult?.corrected || pipelineData.draft;
    if (!articleText) return;

    setIsLoading((prev) => ({ ...prev, titles: true }));
    try {
      const result = await pipelineService.generateTitles(articleText, 3);
      setTitleSuggestions(result.titles);
    } catch (error) {
      console.error('Regenerate titles failed:', error);
      alert('제목 재생성에 실패했습니다.');
    }
    setIsLoading((prev) => ({ ...prev, titles: false }));
  }, [revisedResult, proofreadResult, pipelineData.draft]);

  // Page transition variants
  const pageVariants = {
    initial: { opacity: 0, x: 20 },
    animate: { opacity: 1, x: 0 },
    exit: { opacity: 0, x: -20 },
  };

  return (
    <div className="min-h-screen bg-bg-100">
      <AnimatePresence mode="wait">
        {currentPhase === -1 && (
          <motion.div
            key="autowrite"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <AutoWriteView
              onBack={handleGoHome}
              onComplete={handleAutoWriteComplete}
              autoWriteService={pipelineService.autoWriteArticle}
            />
          </motion.div>
        )}

        {currentPhase === 0 && (
          <motion.div
            key="home"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <HomeView
              onStartPipeline={handleStartPipeline}
              onAutoWrite={handleAutoWrite}
              onQuickAction={handleQuickAction}
              savedArticles={savedArticles}
              onLoadArticle={handleLoadArticle}
              onDeleteArticle={handleDeleteArticle}
            />
          </motion.div>
        )}

        {currentPhase === 1 && (
          <motion.div
            key="phase1"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <Phase1View
              onNext={handlePhase1Complete}
              onPhaseClick={handlePhaseClick}
              onHomeClick={handleGoHome}
              initialData={pipelineData.source}
            />
          </motion.div>
        )}

        {currentPhase === 2 && (
          <motion.div
            key="phase2"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <Phase2View
              onNext={handlePhase2Complete}
              onBack={() => setCurrentPhase(1)}
              onPhaseClick={handlePhaseClick}
              onHomeClick={handleGoHome}
              sourceData={pipelineData.source}
              analysisResult={analysisResult}
              isLoading={isLoading.analysis}
            />
          </motion.div>
        )}

        {currentPhase === 3 && (
          <motion.div
            key="phase3"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <Phase3View
              onNext={handlePhase3Complete}
              onBack={() => setCurrentPhase(2)}
              onPhaseClick={handlePhaseClick}
              onHomeClick={handleGoHome}
              angleData={pipelineData.angle}
              generatedDraft={generatedDraft}
              isGenerating={isLoading.draft}
              onRegenerate={handleRegenerateDraft}
            />
          </motion.div>
        )}

        {currentPhase === 4 && (
          <motion.div
            key="phase4"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <Phase4View
              onNext={handlePhase4Complete}
              onBack={() => setCurrentPhase(3)}
              onPhaseClick={handlePhaseClick}
              onHomeClick={handleGoHome}
              draftData={{ draft: pipelineData.draft || generatedDraft }}
              proofreadResult={proofreadResult}
              revisedResult={revisedResult}
              isProcessing={isLoading.proofread}
              onReprocess={handleReprocess}
            />
          </motion.div>
        )}

        {currentPhase === 5 && (
          <motion.div
            key="phase5"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <Phase5View
              onComplete={handlePipelineComplete}
              onBack={() => setCurrentPhase(4)}
              onPhaseClick={handlePhaseClick}
              onHomeClick={handleGoHome}
              articleData={{
                finalDraft: proofreadResult?.corrected || pipelineData.draft,
              }}
              titleSuggestions={titleSuggestions}
              isGenerating={isLoading.titles}
              onRegenerateTitles={handleRegenerateTitles}
            />
          </motion.div>
        )}

        {currentPhase === 6 && (
          <motion.div
            key="completion"
            variants={pageVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{ duration: 0.3 }}
          >
            <CompletionView
              articleData={{
                title: pipelineData.title,
                finalArticle: pipelineData.finalArticle,
                draft: proofreadResult?.corrected || pipelineData.draft,
              }}
              onNewArticle={handleNewArticle}
              onSaveArticle={handleSaveArticle}
            />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default PipelineContainer;
