import React, { useState, useCallback, useEffect, useRef } from "react";
import { motion } from "framer-motion";
import { Zap, ArrowLeft, Loader2, FileText, Copy, Check, RotateCcw, Wifi, WifiOff, Bot } from "lucide-react";
import { autoWriteWithStreaming, disconnectAutoWrite, isAutoWriteConnected } from "../services/autoWriteWebSocket";

const AutoWriteView = ({
  onBack,
  onComplete,
  autoWriteService, // HTTP fallback (not used in WebSocket mode)
}) => {
  const [sourceText, setSourceText] = useState("");
  const [articleType, setArticleType] = useState("corporate");
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState(null);
  const [streamingText, setStreamingText] = useState("");
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [wsConnected, setWsConnected] = useState(false);
  const [currentAgent, setCurrentAgent] = useState(null);
  const [processingStatus, setProcessingStatus] = useState("");

  const resultRef = useRef(null);

  // Check WebSocket connection status
  useEffect(() => {
    const checkConnection = () => {
      setWsConnected(isAutoWriteConnected());
    };

    checkConnection();
    const interval = setInterval(checkConnection, 3000);

    return () => {
      clearInterval(interval);
      disconnectAutoWrite();
    };
  }, []);

  // Auto-scroll result area during streaming
  useEffect(() => {
    if (resultRef.current && streamingText) {
      resultRef.current.scrollTop = resultRef.current.scrollHeight;
    }
  }, [streamingText]);

  const handleSubmit = useCallback(async () => {
    if (!sourceText.trim()) {
      setError("소재를 입력해주세요.");
      return;
    }

    setIsProcessing(true);
    setError(null);
    setResult(null);
    setStreamingText("");
    setCurrentAgent(null);
    setProcessingStatus("연결 중...");

    try {
      const response = await autoWriteWithStreaming(
        sourceText,
        {
          mode: "full",
          articleType,
        },
        {
          onStart: (message) => {
            console.log("Processing started:", message);
            setProcessingStatus(message.message || "기사 생성을 시작합니다...");
          },
          onChunk: (chunk, fullText, message) => {
            setStreamingText(fullText);
            setProcessingStatus("기사 작성 중...");
          },
          onAgentUpdate: (message) => {
            console.log("Agent update:", message);
            setCurrentAgent(message.agent);
            setProcessingStatus(message.status || `${message.agent} 작업 중...`);
          },
          onComplete: (finalResult, message) => {
            console.log("Processing complete:", message);
            setResult(finalResult);
            setStreamingText("");
            setProcessingStatus("");
          },
          onError: (err) => {
            console.error("Processing error:", err);
            setError(err.message || "기사 생성 중 오류가 발생했습니다.");
            setProcessingStatus("");
          },
        }
      );

      if (response.success) {
        setResult(response.result);
      } else {
        setError(response.error || "기사 생성에 실패했습니다.");
      }
    } catch (err) {
      console.error("Auto write error:", err);
      setError(err.message || "기사 생성 중 오류가 발생했습니다.");
    } finally {
      setIsProcessing(false);
      setProcessingStatus("");
      setCurrentAgent(null);
    }
  }, [sourceText, articleType]);

  const handleCopy = useCallback(() => {
    const textToCopy = result || streamingText;
    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [result, streamingText]);

  const handleReset = useCallback(() => {
    setSourceText("");
    setResult(null);
    setStreamingText("");
    setError(null);
    setCurrentAgent(null);
    setProcessingStatus("");
  }, []);

  const handleUseArticle = useCallback(() => {
    const articleText = result || streamingText;
    if (articleText && onComplete) {
      onComplete({
        title: "자동 생성된 기사",
        article: articleText,
        isAutoGenerated: true,
      });
    }
  }, [result, streamingText, onComplete]);

  // Display text (streaming or final)
  const displayText = result || streamingText;

  return (
    <div className="min-h-screen bg-bg-100 py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              className="p-2 rounded-xl hover:bg-bg-200 transition-colors"
            >
              <ArrowLeft className="w-5 h-5 text-text-300" />
            </button>
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600">
                <Zap className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-semibold text-text-100">자동 기사 작성</h1>
                <p className="text-sm text-text-400">AI가 소재를 분석하고 기사를 완성합니다</p>
              </div>
            </div>
          </div>

          {/* WebSocket Status */}
          <div className="flex items-center gap-2 text-sm">
            {wsConnected ? (
              <span className="flex items-center gap-1 text-green-600">
                <Wifi className="w-4 h-4" />
                실시간 연결
              </span>
            ) : (
              <span className="flex items-center gap-1 text-text-400">
                <WifiOff className="w-4 h-4" />
                대기 중
              </span>
            )}
          </div>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Section */}
          <motion.div
            className="bg-always-white rounded-2xl p-6 shadow-sm border border-border-100"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
          >
            <h2 className="font-medium text-text-100 mb-4 flex items-center gap-2">
              <FileText className="w-4 h-4" />
              소재 입력
            </h2>

            {/* Article Type Selection */}
            <div className="flex gap-2 mb-4">
              <button
                onClick={() => setArticleType("corporate")}
                className={`
                  px-4 py-2 rounded-xl text-sm font-medium transition-all
                  ${articleType === "corporate"
                    ? "bg-text-100 text-bg-000"
                    : "bg-bg-100 text-text-300 hover:bg-bg-200"
                  }
                `}
              >
                기업 보도자료
              </button>
              <button
                onClick={() => setArticleType("public")}
                className={`
                  px-4 py-2 rounded-xl text-sm font-medium transition-all
                  ${articleType === "public"
                    ? "bg-text-100 text-bg-000"
                    : "bg-bg-100 text-text-300 hover:bg-bg-200"
                  }
                `}
              >
                정부/공공
              </button>
            </div>

            {/* Source Text Input */}
            <textarea
              value={sourceText}
              onChange={(e) => setSourceText(e.target.value)}
              placeholder="보도자료, 인터뷰 메모, 참고자료 등을 붙여넣으세요..."
              className="
                w-full h-64 p-4 rounded-xl
                bg-bg-100 border border-border-100
                text-text-100 placeholder-text-400
                resize-none focus:outline-none focus:ring-2 focus:ring-blue-500/20
                transition-all
              "
              disabled={isProcessing}
            />

            {/* Character Count */}
            <div className="flex justify-between items-center mt-2">
              <span className="text-xs text-text-400">
                {sourceText.length.toLocaleString()}자
              </span>
              {sourceText.length < 100 && sourceText.length > 0 && (
                <span className="text-xs text-amber-500">
                  더 많은 내용을 입력하면 좋은 결과를 얻을 수 있습니다
                </span>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <motion.div
                className="mt-4 p-4 rounded-xl bg-red-50 text-red-600 text-sm"
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
              >
                {error}
              </motion.div>
            )}

            {/* Submit Button */}
            <button
              onClick={handleSubmit}
              disabled={isProcessing || !sourceText.trim()}
              className={`
                w-full mt-4 py-4 rounded-xl font-medium
                flex items-center justify-center gap-2
                transition-all duration-300
                ${isProcessing || !sourceText.trim()
                  ? "bg-bg-200 text-text-400 cursor-not-allowed"
                  : "bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:from-blue-700 hover:to-indigo-700 shadow-lg shadow-blue-500/25"
                }
              `}
            >
              {isProcessing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  AI가 기사를 작성하고 있습니다...
                </>
              ) : (
                <>
                  <Zap className="w-5 h-5" />
                  기사 생성하기
                </>
              )}
            </button>

            {/* Processing Status */}
            {isProcessing && (
              <div className="mt-4">
                {currentAgent && (
                  <motion.div
                    className="flex items-center gap-2 text-sm text-blue-600 mb-2"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                  >
                    <Bot className="w-4 h-4" />
                    <span>{currentAgent}</span>
                  </motion.div>
                )}
                <p className="text-center text-xs text-text-400">
                  {processingStatus || "소재 분석, 앵글 선택, 초안 작성, 교열, 퇴고까지 자동으로 진행됩니다"}
                </p>
              </div>
            )}
          </motion.div>

          {/* Result Section */}
          <motion.div
            className="bg-always-white rounded-2xl p-6 shadow-sm border border-border-100"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: 0.1 }}
          >
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-medium text-text-100 flex items-center gap-2">
                생성된 기사
                {isProcessing && streamingText && (
                  <span className="text-xs text-blue-500 animate-pulse">실시간 스트리밍</span>
                )}
              </h2>
              {displayText && (
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="p-2 rounded-lg hover:bg-bg-100 transition-colors"
                    title="복사하기"
                  >
                    {copied ? (
                      <Check className="w-4 h-4 text-green-500" />
                    ) : (
                      <Copy className="w-4 h-4 text-text-400" />
                    )}
                  </button>
                  <button
                    onClick={handleReset}
                    className="p-2 rounded-lg hover:bg-bg-100 transition-colors"
                    title="다시 작성"
                    disabled={isProcessing}
                  >
                    <RotateCcw className="w-4 h-4 text-text-400" />
                  </button>
                </div>
              )}
            </div>

            {displayText ? (
              <>
                <div
                  ref={resultRef}
                  className={`
                    h-64 overflow-y-auto p-4 rounded-xl
                    bg-bg-100 border border-border-100
                    text-text-100 text-sm leading-relaxed
                    whitespace-pre-wrap
                    ${isProcessing ? 'border-blue-200' : ''}
                  `}
                  style={{ fontFamily: "Georgia, 'Noto Serif KR', serif" }}
                >
                  {displayText}
                  {isProcessing && (
                    <span className="inline-block w-2 h-4 bg-blue-500 animate-pulse ml-1" />
                  )}
                </div>

                {/* Word count */}
                <div className="flex justify-between items-center mt-2 text-xs text-text-400">
                  <span>{displayText.length.toLocaleString()}자</span>
                  {result && <span className="text-green-500">완료</span>}
                </div>

                {/* Use Article Button */}
                {result && (
                  <button
                    onClick={handleUseArticle}
                    className="
                      w-full mt-4 py-4 rounded-xl font-medium
                      bg-text-100 text-bg-000 hover:bg-text-200
                      transition-all duration-300
                      flex items-center justify-center gap-2
                    "
                  >
                    <FileText className="w-5 h-5" />
                    이 기사 사용하기
                  </button>
                )}
              </>
            ) : (
              <div className="h-64 flex items-center justify-center text-text-400">
                {isProcessing ? (
                  <div className="text-center">
                    <Loader2 className="w-8 h-8 animate-spin mx-auto mb-3 text-blue-500" />
                    <p>기사 생성 중...</p>
                    <p className="text-xs mt-1">잠시만 기다려주세요</p>
                  </div>
                ) : (
                  <div className="text-center">
                    <Zap className="w-8 h-8 mx-auto mb-3 opacity-30" />
                    <p>소재를 입력하고 생성 버튼을 눌러주세요</p>
                  </div>
                )}
              </div>
            )}
          </motion.div>
        </div>

        {/* Info Section */}
        <motion.div
          className="mt-6 p-4 rounded-xl bg-blue-50 border border-blue-100"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <h3 className="font-medium text-blue-900 mb-2">Multi-Agent AI 시스템</h3>
          <p className="text-sm text-blue-700">
            Supervisor Agent가 Detector, Writer, Quality, Title Agent를 조율하여 기사를 자동으로 완성합니다.
            언어 감지, 카테고리 분류, 보도자료 분석부터 최종 기사 작성까지 전 과정이 자동화됩니다.
            WebSocket 연결로 실시간 스트리밍을 지원합니다.
          </p>
        </motion.div>
      </div>
    </div>
  );
};

export default AutoWriteView;
